// automatically generated by the FlatBuffers compiler, do not modify

package accesslogcounts

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccessLogCounts struct {
	_tab flatbuffers.Table
}

func GetRootAsAccessLogCounts(buf []byte, offset flatbuffers.UOffsetT) *AccessLogCounts {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccessLogCounts{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AccessLogCounts) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccessLogCounts) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccessLogCounts) List(obj *AccessLogCount, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AccessLogCounts) ListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AccessLogCountsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AccessLogCountsAddList(builder *flatbuffers.Builder, List flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(List), 0)
}
func AccessLogCountsStartListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AccessLogCountsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
