// automatically generated by the FlatBuffers compiler, do not modify

package accessLogs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccessLogs struct {
	_tab flatbuffers.Table
}

func GetRootAsAccessLogs(buf []byte, offset flatbuffers.UOffsetT) *AccessLogs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccessLogs{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AccessLogs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccessLogs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccessLogs) List(obj *AccessLog, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AccessLogs) ListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AccessLogsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AccessLogsAddList(builder *flatbuffers.Builder, List flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(List), 0)
}
func AccessLogsStartListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AccessLogsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
